<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class ShopController extends Controller
{
    public function __invoke(): View
    {
        return view('shop', [
            'cartTotal' => 'Rs. 1,130',
            'pageTitle' => 'All Products',
            'products' => $this->products(),
        ]);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function products(): array
    {
        return [
            [
                'id' => 'premium-dried-mango-slices',
                'slug' => 'premium-dried-mango-slices',
                'image' => 'https://images.unsplash.com/photo-1606313564200-e75d5e304d0e?w=600&q=80',
                'hoverImage' => 'https://images.unsplash.com/photo-1608797178974-15b35a8edeaa?w=600&q=80',
                'alt' => 'Dried Mango',
                'name' => 'Premium Dried Mango Slices',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 450',
                'priceNumeric' => 450,
                'comparePrice' => 'Rs. 560',
                'comparePriceNumeric' => 560,
                'onSale' => true,
                'rating' => 4.5,
                'reviews' => 24,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'organic-dried-banana-chips',
                'slug' => 'organic-dried-banana-chips',
                'image' => 'https://images.unsplash.com/photo-1571771894821-ce9b6d11d08e?w=600&q=80',
                'hoverImage' => 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80',
                'alt' => 'Dried Banana',
                'name' => 'Organic Dried Banana Chips',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 320',
                'priceNumeric' => 320,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4,
                'reviews' => 18,
                'inStock' => false,
                'href' => url('/products/organic-dried-banana-chips'),
            ],
            [
                'id' => 'mixed-berry-medley',
                'slug' => 'mixed-berry-medley',
                'image' => 'https://images.unsplash.com/photo-1615485925511-ef4e2b6d4e6e?w=600&q=80',
                'hoverImage' => 'https://images.unsplash.com/photo-1599599810699-26642f847449?w=600&q=80',
                'alt' => 'Mixed Berries',
                'name' => 'Mixed Berry Medley Pack',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 680',
                'priceNumeric' => 680,
                'comparePrice' => 'Rs. 750',
                'comparePriceNumeric' => 750,
                'onSale' => true,
                'rating' => 5,
                'reviews' => 31,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'sun-dried-kiwi',
                'slug' => 'sun-dried-kiwi',
                'image' => 'https://images.unsplash.com/photo-1599599810699-26642f847449?w=600&q=80',
                'alt' => 'Dried Kiwi',
                'name' => 'Sun-Dried Kiwi Slices',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 520',
                'priceNumeric' => 520,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4.5,
                'reviews' => 12,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'himalayan-trail-mix',
                'slug' => 'himalayan-trail-mix',
                'image' => 'https://images.unsplash.com/photo-1608797178974-15b35a8edeaa?w=600&q=80',
                'alt' => 'Trail Mix',
                'name' => 'Himalayan Trail Mix 250g',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 395',
                'priceNumeric' => 395,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4,
                'reviews' => 9,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'golden-dried-pineapple',
                'slug' => 'golden-dried-pineapple',
                'image' => 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80',
                'alt' => 'Dried Pineapple',
                'name' => 'Golden Dried Pineapple Rings',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 410',
                'priceNumeric' => 410,
                'comparePrice' => 'Rs. 480',
                'comparePriceNumeric' => 480,
                'onSale' => true,
                'rating' => 5,
                'reviews' => 27,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'turkish-dried-apricots',
                'slug' => 'turkish-dried-apricots',
                'image' => 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&q=80',
                'alt' => 'Dried Apricot',
                'name' => 'Turkish Dried Apricots',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 580',
                'priceNumeric' => 580,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4.5,
                'reviews' => 15,
                'inStock' => false,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'toasted-coconut-chips',
                'slug' => 'toasted-coconut-chips',
                'image' => 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=600&q=80',
                'alt' => 'Dried Coconut',
                'name' => 'Toasted Coconut Chips',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 290',
                'priceNumeric' => 290,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4,
                'reviews' => 8,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'premium-dried-anjeer',
                'slug' => 'premium-dried-anjeer',
                'image' => 'https://images.unsplash.com/photo-1599599810769-0a29d5affa8e?w=600&q=80',
                'alt' => 'Anjeer',
                'name' => 'Premium Dried Anjeer (Fig)',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 890',
                'priceNumeric' => 890,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 5,
                'reviews' => 42,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'traditional-mango-pickle',
                'slug' => 'traditional-mango-pickle',
                'image' => 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=600&q=80',
                'alt' => 'Mango Pickle',
                'name' => 'Traditional Mango Pickle',
                'category' => 'pickles',
                'categoryLabel' => 'Pickles',
                'price' => 'Rs. 350',
                'priceNumeric' => 350,
                'comparePrice' => null,
                'comparePriceNumeric' => null,
                'onSale' => false,
                'rating' => 4.5,
                'reviews' => 36,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'lime-pickle',
                'slug' => 'lime-pickle',
                'image' => 'https://images.unsplash.com/photo-1588168333706-8819ee0f622a?w=600&q=80',
                'alt' => 'Lime Pickle',
                'name' => 'Spicy Lime Pickle',
                'category' => 'pickles',
                'categoryLabel' => 'Pickles',
                'price' => 'Rs. 280',
                'priceNumeric' => 280,
                'comparePrice' => 'Rs. 320',
                'comparePriceNumeric' => 320,
                'onSale' => true,
                'rating' => 4,
                'reviews' => 14,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
            [
                'id' => 'festive-gift-box',
                'slug' => 'festive-gift-box',
                'image' => 'https://images.unsplash.com/photo-1606313564200-e75d5e304d0e?w=600&q=80',
                'alt' => 'Gift Box',
                'name' => 'Festive Dry Fruit Gift Box',
                'category' => 'dried-fruits',
                'categoryLabel' => 'Dried Fruits',
                'price' => 'Rs. 2,450',
                'priceNumeric' => 2450,
                'comparePrice' => 'Rs. 2,800',
                'comparePriceNumeric' => 2800,
                'onSale' => true,
                'rating' => 5,
                'reviews' => 58,
                'inStock' => true,
                'href' => url('/products/premium-dried-mango-slices'),
            ],
        ];
    }
}
